services:
  - type: web
    name: vida-plena-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_TYPE
        value: postgres
      - key: DATABASE_HOST
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: DATABASE_PORT
        value: 5432
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000 